name:  ExplodingEggs
version:  1.2.2
author:  GudfareN
main: me.GudfareN.ExplodingEggs.Main

commands:
   ee:
      description: Toggle egg explosion
      permission: ee.toggle
      usage: /ee
   eeinfo:
      description: Toggle egg explosion
      usage: /eeinfo