name:  ExplodingEggs
version:  1
author:  GudfareN
main: me.GudfareN.ExplodingEggs.Main

commands:
   ee:
      description: Toggle egg explosion
      permission: ee.toggle
      usage: /ee
   er:
      description: Toggle random explosion
      permission: ee.toggleRandom
      usage: /er